# Dockerfile for orchestrator
# TO DO: Reduce image size with multi stage build
FROM golang:alpine

# Set necessary environmet variables needed for our image
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 

# Move to working directory /build
WORKDIR /build

# Copy and download dependency using go mod
COPY go.mod .
COPY go.sum .
RUN go mod download

# Copy the code into the container
COPY . .

# Copy edgepipeline package directory
ADD edgepipeline ./edgepipeline

# Build the application
RUN go build -o main .

# Command to run when starting the container
ENTRYPOINT ["/build/main"]

# For Debug using attach shell
#ENTRYPOINT ["tail", "-f", "/dev/null"]
